///* generated by dia/codegen.py */
///*(NULL)*/
//class MappingDemo
//{
//private:
//	void demo ();
//};
//
///*(NULL)*/
//class NavigationDemo
//{
//private:
//	void demo ();
//};
//
///*(NULL)*/
//class Map
//{
//public:
//	 build_map ();
//	 save_map ();
//};
//
///*(NULL)*/
//class GlobalPathPlanner
//{
//public:
//	void initialize (std::string  name,
//	                 costmap_2d::Costmap2DROS costmap);
//	bool make_plan (geometry_msgs::PoseStamped start,
//	                geometry_msgs::PoseStamped goal,
//	                std::vector<geometry_msgs::PoseStamped> plan);
//	  (std::string name name,
//	   costmap_2d::Costmap2DROS costmap);
//};
//
///*(NULL)*/
//class Navigate
//{
//public:
//	 get_stop_location ();
//	 global_navigate ();
//	 local_navigate ();
//};
//
